[package]
name = "fuji"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.26"
once_cell = "1.20.3"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
snafu = "0.8.5"
strum = "0.27.1"
strum_macros = "0.27.1"
